### ISSUE TITLE
Use TermInfo instead of multiple strings in similarity.yaml

### ISSUE THREAD

**Issue by julesjacobsen** [INCATools/ontology-access-kit#328]
There are a lot of string fields using field names to group them into entities which would likely be better as `TermInfo` types. e.g.

```yaml
classes:
  PairwiseSimilarity:
    abstract: true
    description: >-
      Abstract grouping for representing individual pairwise similarities

  TermPairwiseSimilarity:
    is_a: PairwiseSimilarity
    description: >-
      A simple pairwise similarity between two atomic concepts/terms
    slots:
      # there are a lot of stringly-typed entities here, shouldn't these be TermInfo types?
      - subject_id
      - subject_label
      - subject_source
      - object_id
      - object_label
      - object_source
      - ancestor_id
      - ancestor_label
      - ancestor_source
      - object_information_content
      - subject_information_content
      - ancestor_information_content
      - jaccard_similarity
      - dice_similarity
      - phenodigm_score

...
```

This would be far more usable like so:

```yaml
classes:
  PairwiseSimilarity:
    abstract: true
    description: >-
      Abstract grouping for representing individual pairwise similarities

  TermPairwiseSimilarity:
    is_a: PairwiseSimilarity
    description: >-
      A simple pairwise similarity between two atomic concepts/terms
    attributes:
      subject:
        range: TermInfo
        required: true
      object:
        range: TermInfo
        required: true
      ancestor:
        range: TermInfo
        required: true
        description: >-
          the most recent common ancestor of the two compared entities. If there are multiple MRCAs then
          the most informative one is selected
    slots:
      - object_information_content
      - subject_information_content
      - ancestor_information_content
      - jaccard_similarity
      - dice_similarity
      - phenodigm_score

  TermSetPairwiseSimilarity:
    is_a: PairwiseSimilarity
    description: >-
      A simple pairwise similarity between two sets of concepts/terms
    attributes:
      subject_termset:
        range: TermInfo
        multivalued: true
      object_termset:
        range: TermInfo
        multivalued: true
      subject_best_matches:
        range: BestMatch
        multivalued: true
        inlined:
      object_best_matches:
        range: BestMatch
        multivalued: true
      best_score:
        range: float
        required: true
      average_score:
        range: float
        required: true
      metric:
        range: uriorcurie

  TermInfo:
    attributes:
      id:
        identifier: true
      label:
        slot_uri: rdfs:label

  BestMatch:
    attributes:
      source:
        range: TermInfo
        required: true
        comments:
          - note that the match_source is either the subject or the object
      target:
        range: TermInfo
        required: true
        description: the entity matches
      score:
        range: float
        required: true
      subsumer:
        range: TermInfo
        required: true
      similarity:
        range: TermPairwiseSimilarity
        required: true

```
