### ISSUE TITLE
Add a dynamic ValueSet expander

### ISSUE THREAD

**Issue by cmungall** [INCATools/ontology-access-kit#370]
For full context, see:

 - https://douroucouli.wordpress.com/2022/07/15/using-ontologies-within-data-models-and-standards/
 - https://build.fhir.org/valueset-operation-expand.html

We would like a method that takes a value set like

```yaml
  GoMembrane:
    pv_formula: CURIE
    reachable_from:
      include_self: true
      source_ontology: obo:go
      source_nodes:
        - GO:0016020 ## membrane
```

and adds in all permissible values:

```yaml
    permissible_values:
      GO:0090512:
        text: GO:0090512
        description: eisosome membrane domain/MCC
        meaning: GO:0090512
      GO:0000421:
        text: GO:0000421
        description: autophagosome membrane
        meaning: GO:0000421
      GO:0009279:
        text: GO:0009279
        description: cell outer membrane
        meaning: GO:0009279
      GO:0005778:
...
```

This could take an optional configuration file like this:

```
resource_resolvers:
  bioregistry:wikidata:
    shorthand: "wikidata:"
prefix_resolvers:
  obo:
    shorthand_prefix: "sqlite:obo"
```

That would map different `source_ontology` values to different adapters/implementations

Currently only backends supported by OAK would be used (sqlite, obo, owl, bioportal, ols, ubergraph, ...) but in future a FHIR backend could be used - see #351

This should work for both fhir value sets and linkml value sets, but we can proceed incrementally starting with the latter
