### ISSUE TITLE
include contributors and roles in summary statistics

### ISSUE THREAD

**Issue by cmungall** [INCATools/ontology-access-kit#378]
Currently running `statistics` on an ontology will yield detailed summary statistics (optionally broken down by properties such as prefix or obo namespace). This include class count etc.

e.g

```yaml
id: obo:go/releases/2022-11-03/extensions/go-plus.owl-statistics
ontologies:
- id: obo:go/extensions/go-plus.owl
  version: obo:go/releases/2022-11-03/extensions/go-plus.owl
  version_info: '2022-11-03'
partitions:
  biological_process:
    annotation_property_count: 0
    class_count: 30498
    class_count_by_subset:
      obo:go#gocheck_do_not_annotate:
        facet: obo:go#gocheck_do_not_annotate
        filtered_count: 220
      obo:go#gocheck_do_not_manually_annotate:
        facet: obo:go#gocheck_do_not_manually_annotate
        filtered_count: 73
...
   class_count_with_text_definitions: 30498
    class_count_without_text_definitions: 0
    deprecated_class_count: 2505
    deprecated_property_count: 0
    distinct_synonym_count: 93036
    edge_count_by_predicate:
      BFO:0000050:
        facet: BFO:0000050
        filtered_count: 5027
      BFO:0000051:
        facet: BFO:0000051
        filtered_count: 413
...
```

The yaml here is a serialization of [Summary Statistics Data Model](https://incatools.github.io/ontology-access-kit/datamodels/summary-statistics/index.html)

We should extend this to have contributor summaries

This might look like this:

```yaml
    contributor_summary:
      orcid:nnnn-nnnn-nnnn-nnnn:
        contributor_name: <full name>
        role_counts:
          dcterms:contributor: 3
          dcterms:creator: 1
```

Note that OBO is currently undergoing standardization w.r.t contributor roles (see https://github.com/information-artifact-ontology/ontology-metadata/issues/120), but outside of OBO groups do have different roles, so we want to be pluralistic, and also allow the ability to roll up to a broader role/predicate.

We want to use the CURIE/URI of the contributor here, and optionally include the label of the contributor (this can be obtained at query time from orcidio, which is in semsql)

one challenge is that some ontologies still use full name literals for contributors, so for this we could make a uuid/base64 id based on the name OR try and do some run-time name normalization
