### ISSUE TITLE
Bug: `obographs` LinkML: unrecognized slot `allValuesFromEdges` on `domainRangeAxioms`

### ISSUE THREAD

**Issue by joeflack4** [INCATools/ontology-access-kit#413]
## Overview
I'm trying to load an Obograph into OAK. I got an error for an unrecognized property `allValuesFromEdges` within my `domainRangeAxioms`.

## Error
Short err: `ValueError:  Unknown argument: allValuesFromEdges = [{'sub': 'http://purl.obolibrary.org/obo`

## Possible solutions
I looked at `src/oaklib/datamodels/obograph.yml`:
```yaml
  DomainRangeAxiom:
    is_a: Axiom
    slots:
      - predicateId
      - domainClassIds
      - rangeClassIds
```

I suppose that `allValuesFromEdges` needs to be added as a slot to `DomainRangeAxiom`. I could probably make this update, but I need a bit more time to figure out what to do. I think something like the below, but I don't know what to put for `range`.

```yaml
  allValuesFromEdges:
    multivalued: true
    range: ???
```

Here's an example of `allValuesFromEdges` in an Obographs JSON:
```json
          "allValuesFromEdges": [
            {
              "sub": "http://purl.obolibrary.org/obo/CL_0000000",
              "pred": "http://purl.obolibrary.org/obo/RO_0002207",
              "obj": "http://purl.obolibrary.org/obo/CL_0000000"
            },
           ...
```
