### ISSUE TITLE
lexmatch should utilize xrefs in both directions when generating candidate mappings

### ISSUE THREAD

**Issue by cmungall** [INCATools/ontology-access-kit#585]
given an ontology:

```yaml
[Term]
id: CL:1
xref: FBbt:1

[Term]
id: UBERON:2
xref: FBbt:2
xref: ZFA:2

[Term]
id: ZFA:1
name: zfa1
xref: CL:1

[Term]
id: ZFA:2
name: zfa2

[Term]
id: UBERON:2
xref: ZFA:2
xref: FBbt:2
```

when matching ZFA and FBbt, both terms should match:

1. should match due to shared CL mapping
2. should match due to a shared UBERON mapping

This should be regardless of direction

- for CL, ZFA xrefs to CL, CL xrefs to FBbt
- for UBERON, neither MOD xrefs to UBERON, but UBERON xrefs to both

Furthermore the direction should be distinguishable for rule purposes (e.g weighting xrefs from one source vs another)

Note: this example uses xrefs due to their ubiquity but the same holds for any mapping predicate
