### ISSUE TITLE
Add logic to infer skos mapping predicate based on axiom annotation

### ISSUE THREAD

**Issue by cmungall** [INCATools/ontology-access-kit#611]
GO:

```yaml
id: GO:0016805
name: dipeptidase activity
def: "Catalysis of the hydrolysis of a dipeptide." [https://www.ebi.ac.uk/merops/about/glossary.shtml#DIPEPTIDASE, PMID:19879002]
synonym: "cytosolic dipeptidase activity" NARROW []
xref: EC:3.4.13.-
xref: EC:3.4.13.18 {source="skos:narrowMatch"}
xref: EC:3.4.13.21 {source="skos:narrowMatch"}
xref: MetaCyc:3.4.13.18-RXN {source="skos:narrowMatch"}
xref: MetaCyc:3.4.13.18-RXN
xref: MetaCyc:3.4.13.21-RXN {source="skos:narrowMatch"}
is_a: GO:0008238 ! exopeptidase activity
```

Note: this is how it looks in the release and in the edit version

Thus running OAK over the release version uses hasDbXref in the SSSOM datamodel:

`go mappings GO:0016805 -M EC`:

```yaml
subject_id: GO:0016805
predicate_id: oio:hasDbXref
object_id: EC:3.4.13.-
mapping_justification: semapv:UnspecifiedMatching
subject_label: dipeptidase activity
subject_source: GO
object_source: EC

---
subject_id: GO:0016805
predicate_id: oio:hasDbXref
object_id: EC:3.4.13.18
mapping_justification: semapv:UnspecifiedMatching
subject_label: dipeptidase activity
subject_source: GO
object_source: EC

---
subject_id: GO:0016805
predicate_id: oio:hasDbXref
object_id: EC:3.4.13.21
mapping_justification: semapv:UnspecifiedMatching
subject_label: dipeptidase activity
subject_source: GO
object_source: EC
```

MONDO:

```yaml
id: MONDO:0018308
name: liver mesenchymal hamartoma
def: "A multicystic, tumor-like hamartomatous lesion that arises from the liver during fetal development. Clinically, it usually presents as an abdominal mass associated with abdominal distention. Following resection, the prognosis is usually good." [NCIT:C5751]
comment: Editor note: in NCIT this is classified as non-neoplastic
subset: gard_rare {source="GARD:0002651"}
subset: ordo_disease {source="Orphanet:386"}
synonym: "biliary hamartoma" EXACT [Orphanet:386]
synonym: "hepatic cystic hamartoma" RELATED [Orphanet:386]
synonym: "hepatic mesenchymal hamartoma" EXACT [NCIT:C5751]
synonym: "liver mesenchymal hamartoma" EXACT [MONDO:patterns/location, NCIT:C5751]
synonym: "liver MH" EXACT [NCIT:C5751]
synonym: "mesenchymal hamartoma of liver" EXACT [NCIT:C5751, Orphanet:386]
synonym: "mesenchymal hamartoma of the liver" EXACT [NCIT:C5751]
synonym: "MHL" EXACT ABBREVIATION [Orphanet:386]
synonym: "VMC" EXACT ABBREVIATION [Orphanet:386]
synonym: "Von Meyenburg complexes disease" EXACT [Orphanet:386]
xref: GARD:0002651 {source="MONDO:equivalentTo"}
xref: ICD10CM:D13.4 {source="Orphanet:386/btnt", source="Orphanet:386"}
xref: NCIT:C5751 {source="MONDO:equivalentTo"}
xref: Orphanet:386 {source="MONDO:equivalentTo"}
xref: SCTID:715397000 {source="MONDO:equivalentTo"}
xref: UMLS:C0334091 {source="MONDO:equivalentTo", source="Orphanet:386"}
xref: UMLS:C1333971 {source="MONDO:equivalentTo", source="NCIT:C5751"}
```

Note: this is how it looks in the edit version, but in the release version these are replaced by skos predicates. Thus OAK gives correct yet duplicative results:

`mondo mappings MONDO:0018308 -M NCIT`

```yaml
mondo mappings MONDO:0018308 -M NCIT
subject_id: MONDO:0018308
predicate_id: oio:hasDbXref
object_id: NCIT:C5751
mapping_justification: semapv:UnspecifiedMatching
subject_label: liver mesenchymal hamartoma
subject_source: MONDO
object_source: NCIT

---
subject_id: MONDO:0018308
predicate_id: skos:exactMatch
object_id: NCIT:C5751
mapping_justification: semapv:UnspecifiedMatching
subject_label: liver mesenchymal hamartoma
subject_source: MONDO
object_source: NCIT
```

Should we:

1. use axiom annotations to infer predicate in OAK
2. assume that eventually ontologies will include skos in release product (@balhoff)
     - a. duplicate xref+literal and skos+iri (Mondo)
     - b. skos only?

I think 2a should be what we are working towards. We may still want some logic in OAK to optionally de-dupe xrefs into skos?

cc @matentzn @hrshdhgd
