### ISSUE TITLE
Handling equivalence node sets in graph operations such as semantic similarity

### ISSUE THREAD

**Issue by cmungall** [INCATools/ontology-access-kit#634]
With OWL ontologies it is possible to have *equivalence sets*, a set of named classes that are mutually equivalent. Each class is in an equivalence set of size at least 1.

The OWLAPI reasoner API treats an equivalence set as a first-class object (it calls it a *node*), and operations are on these sets.

In contrast, OAK has a more graph-oriented view and doesn't treat an equivalence set as first-class, and equivalency is treated as just another predicate that can be traversed (it is also able to handle the situation where equivalence is relaxed to reciprocal is-as, even though we don't recommend distributing ontologies that way). Note that the obographviz visualization *does* have a way to generate equivalence sets for visualization, but this is best understood as post processing.

so given:

```yaml
[Term]
id: X:1

[Term]
id: X:1a
is_a: X:1

[Term]
id: X:1b
is_a: X:1

[Term]
id: Y:1
equivalent_to: X:1

[Term]
id: Y:1a
is_a: Y:1
equivalent_to: X:1a

[Term]
id: Y:1b
is_a: Y:1
equivalent_to: X:1b
```

operations will work:

`runoak -i simpleobo:tests/input/graph-with-equivs.obo viz .all`

resulting in:

<img width="649" alt="image" src="https://github.com/INCATools/ontology-access-kit/assets/50745/00815198-4079-4077-a5b2-b8f90022a8e6">

but for some purposes, we may want to treat these nodes *as if* they were collapsed into equivalence sets.

For example, for semantic similarity purposes, we might want to count each equivalence set once, rather than each individual class, for statistical purposes.

Some approaches are:

1. treat equivalence sets as first class, as per the OWLAPI
2. rely on the user to merge ahead of time, and allow for lookup operations on queries

Approach 1 would be quite a large lift, and may entail even some rethinking at the RG level.

To see how 2 would work, we would first do a merge:

`owltools  tests/input/graph-with-equivs.obo --reasoner elk  --merge-equivalence-sets -o -f obo tests/input/graph-with-equivs-merged.obo`

(merge is not supported in OAK but this would actually be a very easy lift)

```yaml
[Term]
id: X:1b
xref: Y:1b
is_a: Y:1

[Term]
id: Y:1
xref: X:1

[Term]
id: Y:1a
xref: X:1a
is_a: Y:1
```

(owltools has various configs for deciding which ID space to prioritize - in the above it is arbitrary)

Note that owltools predates sssom, if we were to do this in OAK we could use skos exact match... or we could simply leave the equivalence axiom in place but ensure transfer to a canonical node.

A variant of this approach is to generate entirely new IDs so as not to favor one ID space. The principle is the same

It is then the responsibility of the caller to

1. map from query IDs to normalized IDs prior to calling OAK commands
2. rewriting outputs from normalized IDs to user-preferred IDs (or sets of IDs)

It is in fact already possible to do 1. directly in OAK itself. 2 is not directly supported but is easy to chain together.

**Comment by matentzn** [comment]
There is a third strategy, which sounds very idiosyncratic, but maybe the best for the semantic similarity use case.

Both of your strategies have problems: leaving the user to the complexities of picking clique leaders is one; but the more serious issue is that we want semantic similarity algorithms to provide results for the whole signature, and not just the signature of the merged ontology (In your example, we want `X:1` to appear in the signature, and, in particular, that there is a similarity tuple `{X:1, Y:1, jaccard:1.0}`. 

So the suggestion for the third strategy is having a method like "runoak propagate-relations -i ont -m mapping.sssom.tsv", where the idea is that all content from nodes is propagated rather than merged. So the outcome is NOT:

```
[Term]
id: X:1b
xref: Y:1b
is_a: Y:1

[Term]
id: Y:1
xref: X:1

[Term]
id: Y:1a
xref: X:1a
is_a: Y:1
```

But:


```
[Term]
id: X:1
equivalent_to: Y:1 # NEW

[Term]
id: X:1a
is_a: X:1
is_a: Y:1 #NEW

[Term]
id: X:1b
is_a: X:1
is_a: Y:1 #NEW
equivalent_to: Y:1b #NEW

[Term]
id: Y:1
equivalent_to: X:1

[Term]
id: Y:1a
is_a: Y:1
is_a: X:1 #NEW
equivalent_to: X:1a

[Term]
id: Y:1b
is_a: Y:1
is_a: X:1 #NEW
equivalent_to: X:1b
```

Note the `equivalent_to: XXX` sections in my vision would be more a skos:exactMatch or even some externally provided SSSOM file.

We could also consider propagating along skos:broadMatch and skos:narrowMatch.

I see this strictly as a preprocessing step for semantic similarity.

**Comment by matentzn** [comment]
As per meeting: since relationgraph already takes care of what I am suggesting above, this whole issue here should not be in issue - I simply need to add the owl:equivalentTo axioms to PHENIO prior to loading it  into semsql and its done! So for now, my issue is solved, and I do not need any further sophisticated ops. (Issue can be closed if you want)

**Comment by cmungall** [comment]
Even though we are on the same page, I extended the example to illustrate the bias scenario:

```yaml
[Term]
id: X:1

[Term]
id: X:1a
is_a: X:1

[Term]
id: X:1b
is_a: X:1

[Term]
id: Y:1
equivalent_to: X:1

[Term]
id: Y:1a
is_a: Y:1
equivalent_to: X:1a

[Term]
id: Y:1b
is_a: Y:1
equivalent_to: X:1b

[Term]
id: Y:1ba
is_a: Y:1b

[Term]
id: X:1bz
is_a: X:1b
```

which looks like this:

<img width="766" alt="image" src="https://github.com/INCATools/ontology-access-kit/assets/50745/5c9b1636-8a66-48e5-970c-0370e9534d5b">

note we have two classes Y:1ba and X:1bz which are unique to their respective ontologies

merging:

`owltools  tests/input/graph-with-equivs.obo --reasoner elk  --merge-equivalence-sets -s X 10 -o -f obo tests/input/graph-with-equivs-merged.obo`

looks like this:

<img width="234" alt="image" src="https://github.com/INCATools/ontology-access-kit/assets/50745/c0d5165d-a004-49c8-bfbe-e4c85538ceb3">

(xrefs not shown)

We can see different scores:

`runoak  -i tests/input/graph-with-equivs.obo similarity -p i,owl:equivalentClass X:1bz @ Y:1ba`

```yaml
subject_id: X:1bz
object_id: Y:1ba
ancestor_id: owl:Thing
ancestor_information_content: 0.0
jaccard_similarity: 0.6666666666666666
```

`runoak  -i tests/input/graph-with-equivs-merged.obo similarity -p i X:1bz @ Y:1ba`

```yaml
subject_id: X:1bz
object_id: Y:1ba
ancestor_id: owl:Thing
ancestor_information_content: 0.0
jaccard_similarity: 0.5
```
